---
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - pip=20.2.*
  - snakemake=5.22.*
  - nanoplot=1.31.*
  - nanofilt=2.7.*
  - nanoqc=0.9.*
  - minimap2=2.*
  - seqkit=0.13.*
  - cutadapt=2.*
  - plotly=4.8.*
  - spoa=4.*
  - seaborn=0.10.*
  - edlib>=1.1.2
  - natsort=7.1.*
  - networkx=2.3.*
  - pip:
      - isONclust
name: mapt_pipeline
