---
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - pip=20.2.*
  - snakemake=5.*
  - nanoplot=1.31.*
  - nanofilt=2.7.*
  - nanoqc=0.9.*
  - minimap2=2.*
  - cutadapt=3.*
  - plotly=4.8.*
  - spoa=4.*
  - seaborn=0.10.*
  - edlib>=1.1.2
  - networkx=2.3.*
  - natsort=7.*             # used by scripts/generateOTU.py
  - autoconf=2.69           # required by isOnclust
  - automake=1.16.*         # required by isOnclust
  - libtool=2.4.*           # required by isOnclust
  - xlsxwriter=1.3.*        # required by statistics generation
  - pip:
      - isONclust
