---
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - pip=20.2.*
  - snakemake=5.*
  - nanoplot=1.31.*
  - nanofilt=2.7.*
  - nanoqc=0.9.*
  - minimap2=2.*
  - seqkit=0.13.*
  - cutadapt=3.*
  - plotly=4.8.*
  - spoa=4.*
  - seaborn=0.10.*
  - edlib>=1.1.2
  - networkx=2.3.*
  - natsort=7.* # used by scripts/generateOTU.py
  - autoconf    # required by isOnclust
  - automake    # required by isOnclust
  - libtool     # required by isOnclust
  - xlsxwriter  # required by statistics generation
  - pip:
      - isONclust
name: mapt_pipeline
