name: pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - pip
  - snakemake=5.22.*
  - nanoplot=1.31.*
  - nanofilt=2.7.*
  - nanoqc=0.9.*
  - vsearch=2.15.*
  - minimap2=2.*
  - seqkit=0.13.*
  - cutadapt=2.*
  - plotly=4.8.*
  - spoa=4.*
  - seaborn=0.10.*
  - pip:
        - IsoCon==0.3.*
        - isONclust==0.*
        - networkx==2.3
