
Bootstrap: docker
From: ubuntu

%help
    Please visit https://www.github.com/JoshLoecker/MAPT for more info

%post
    # this is the version of Guppy we are using
    GUPPY_VERSION=4.4.1

    # update the ubuntu container, install wget
    apt update
    apt install wget --yes

    # download guppy and save it at ~/guppy.deb
    wget -O /guppy.deb https://mirror.oxfordnanoportal.com/software/analysis/ont_guppy_${GUPPY_VERSION}~focal_amd64.deb

    # install guppy and its dependencies
    apt install /guppy.deb --yes

    # do some cleanup on items that are no longer needed
    rm /guppy.deb
    apt purge wget --yes
    apt clean
    apt autoclean
    apt autoremove --yes
    rm -rf /var/lib/{apt,dpkg,cache,log}/

%test
    # This section will test if guppy_barcoder and guppy_basecaller are available
    guppy_barcoder --version
    guppy_basecaller --version
